DROP INDEX IF EXISTS idx_users_online;
DROP INDEX IF EXISTS idx_users_role_status_available;

ALTER TABLE users ALTER COLUMN username TYPE VARCHAR(50);
ALTER TABLE users ALTER COLUMN phone TYPE VARCHAR(20);

ALTER TABLE users DROP COLUMN IF EXISTS last_seen_at;
ALTER TABLE users DROP COLUMN IF EXISTS is_online;
ALTER TABLE users DROP COLUMN IF EXISTS is_active;
ALTER TABLE users DROP COLUMN IF EXISTS rating;
ALTER TABLE users DROP COLUMN IF EXISTS total_sessions;
ALTER TABLE users DROP COLUMN IF EXISTS specialization;
ALTER TABLE users DROP COLUMN IF EXISTS company;
ALTER TABLE users DROP COLUMN IF EXISTS language;
ALTER TABLE users DROP COLUMN IF EXISTS timezone;
ALTER TABLE users DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users DROP COLUMN IF EXISTS full_name;
ALTER TABLE users DROP COLUMN IF EXISTS is_available;
ALTER TABLE users DROP COLUMN IF EXISTS max_sessions;
ALTER TABLE users DROP COLUMN IF EXISTS operator_status;
ALTER TABLE users DROP COLUMN IF EXISTS role;
